### ISSUE TITLE
V5 Crashing after first launch when settings have been modified

### ISSUE THREAD

**Issue by niktn10** [threethan/LightningLauncher#17]
Hello. Tested the new version.
After the update, the application crashes immediately after launch.
During a clean installation, the application starts, but after 5 minutes of running and closing the application, it was no longer possible to start it again. Crashes immediately upon startup.
So far this is all that I have been able to test, as it works very unstable.

UPD
If you don’t customize anything and use it as is, then everything works. It turns out that the crash of the program is somehow related to changing the program settings.

**Comment by threethan** [comment]
> If you don’t customize anything and use it as is, then everything works. It turns out that the crash of the program is somehow related to changing the program settings.
Even on first launch, the app stores a number of values to it's preferences. However, there may be issues with settings not syncing properly with the shortcut service's activity.

Have you been opening LL from "Unknown Sources", using the shortcut service, using the shortcut apk, or some combination?

**Comment by threethan** [comment]
I fixed the issue mentioned above in 5.0.1, let me know if this resolves your issue.

**Comment by siskyn** [comment]
I had the same issue, updated to 5.0.1. It still crashes 50-70 of the time when launched with the accesability service, but now it can recover on future tries as oposed to being completely dead until clearing data as was the case for 5.0.0.

At some point it even shows an error in the accesability settings menu.

I recorded testing in case it hells you notice anything extra: [https://youtu.be/ka8VFsxt9d8](url)

**Comment by threethan** [comment]
Very helpful! The fact that it crashes after setting the background color but before displaying the actual interface narrows it down to a handful of functions.

I've fixed the few crashes I could get on my device and a few possible leaks, pushed as 5.0.2

**Comment by siskyn** [comment]
5.0.2 works like a charm consistently, thanks!

As a little side note, ideas for improvement if / whenever you can / want to:
- Ability to see systems apps (such as Events). Can be moved to hidden if desired easily enough.
- Ability to import / export settings to file
- Search bar
- Ability to change which native app is replaced by the launcher (only relevant if we can't see system apps in the launcher). That way we can still access the original library to launch things like Move or Events, without having them pinned to the dashboard.

**Comment by threethan** [comment]
Have already been looking into these feature requests.
- All apps that are not currently shown on the launcher cannot currently be launched if they were visible, with the sole exception of the air link app which is better operated through the quick settings. This might change in the future if I can find a better way to detect launch intents.
- A search bar would be a great addition, but would require a rework to how apps are filtered and displayed. I'll probably do this eventually.
- I want to add the ability to replace the explore app and/or the app library, but only after I'm sure everything is fully stable

Feel free to open issues for feature request. I'm going to close this one as the issue itself seems to be solved.
