### ISSUE TITLE
Search does no longer find apps from hidden folder

### ISSUE THREAD

**Issue by weini22** [threethan/LightningLauncher#197]
At least in 9.0.3 the search seems to behave strange (definitely different than in pre-9 verions).
I have the setting activated in "advanced settings", that search should also find items from the hidden folder.

But this is not considered any more.
If I´m not mistaken, then search is only finding apps from the currently selected group.

**Comment by threethan** [comment]
This should be resolved in 9.1.0

**Comment by weini22** [comment]
Thanks for looking into this!
Re-tested with 9.1.0, but unfortunately, the problem persists.
